[package]
name = "pqueue_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
uuid = "1.6.1"
