[package]
name = "pqueue_client"
version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
