[package]
name = "pqueue_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
pqueue = { path = "../pqueue" }
tokio = { workspace = true }
uuid = { workspace = true }
